# Generated by Django 4.1.12 on 2024-05-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compare',
            old_name='campare_id',
            new_name='compare_id',
        ),
        migrations.RenameField(
            model_name='compareiteam',
            old_name='campare_id',
            new_name='compare_id',
        ),
    ]
