# Generated by Django 4.1.12 on 2024-05-01 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_rename_campare_id_compare_compare_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compareiteam',
            name='id',
        ),
        migrations.AddField(
            model_name='compareiteam',
            name='compare_item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
