# Generated by Django 5.0.4 on 2024-06-13 08:17

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=225, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), null=True, size=None)),
                ('category_image', models.ImageField(null=True, upload_to='category/')),
            ],
        ),
    ]
