# Generated by Django 5.0.4 on 2024-06-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='sub_category_id',
        ),
    ]
