# Generated by Django 5.0.4 on 2024-06-28 11:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_remove_order_delivery_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, default='SG11112212', editable=False, max_length=10)),
                ('billing_address', models.TextField(blank=True)),
                ('invoice_status', models.CharField(blank=True, default='Unpaid', max_length=50)),
                ('shipping_address', models.TextField(blank=True)),
                ('invoice_image', models.FileField(editable=False, upload_to='invoice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.PositiveIntegerField(default=0)),
                ('gst', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=10)),
                ('customer_notes', models.TextField(blank=True)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), null=True, size=None)),
                ('order', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
