# Generated by Django 5.0.4 on 2024-06-13 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, default='SG11112212', editable=False, max_length=10)),
                ('billing_address', models.TextField(blank=True)),
                ('invoice_status', models.CharField(blank=True, default='Unpaid', max_length=50)),
                ('shipping_address', models.TextField(blank=True)),
                ('invoice_image', models.FileField(editable=False, upload_to='invoice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.PositiveIntegerField(default=0)),
                ('gst', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_mobile_number', models.CharField(blank=True, max_length=10)),
                ('customer_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('invoice_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('discount_price', models.PositiveBigIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sub_category', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('invoice', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
                ('product', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
