# Generated by Django 5.0.4 on 2024-06-12 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_remove_order_delivery_charges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp_initiated', models.DateTimeField(auto_now_add=True)),
                ('timestamp_completed', models.DateTimeField(blank=True, null=True)),
                ('link_id', models.UUIDField(null=True, unique=True)),
                ('user_mobile_no', models.CharField(max_length=10)),
                ('user_email', models.EmailField(max_length=225, null=True)),
                ('order', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
