# Generated by Django 4.1.12 on 2024-05-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
