# Generated by Django 4.1.12 on 2024-05-17 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link_id',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
