# Generated by Django 5.0.4 on 2024-05-17 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('Placed', 'Placed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', editable=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.TextField()),
                ('total_price', models.PositiveBigIntegerField(default=0, editable=False)),
                ('address', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('user', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
