# Generated by Django 5.0.4 on 2024-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
