# Generated by Django 5.0.4 on 2024-06-27 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_stock', models.PositiveBigIntegerField(blank=True, null=True)),
                ('unit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('default_price', models.FloatField(blank=True, null=True)),
                ('regular_selling_price', models.FloatField(blank=True, null=True)),
                ('regular_buying_price', models.FloatField(blank=True, null=True)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('revenue', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sales', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dealer_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product_id', models.OneToOneField(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
