# Generated by Django 5.0.4 on 2024-05-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='hsn_code',
            field=models.CharField(default='IXD32194', editable=False, max_length=8),
        ),
    ]
