# Generated by Django 5.0.4 on 2024-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='hsn_code',
            field=models.CharField(default='ZAJ28690', editable=False, max_length=8),
        ),
    ]
