# Generated by Django 5.0.4 on 2024-05-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stock_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='hsn_code',
            field=models.CharField(default='BLK75376', editable=False, max_length=8),
        ),
    ]
