# Generated by Django 5.0.6 on 2024-05-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stock_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='hsn_code',
            field=models.CharField(default='GCZ15504', editable=False, max_length=8),
        ),
    ]
